formatter: markdown table

header-from: main.tf
footer-from: ""

sections:
  show:
    - header
    - inputs
    - outputs
    - providers
    - requirements
    - resources

content: |-
  {{ .Header }}

  ## Requirements
  {{ .Requirements }}

  ## Providers
  {{ .Providers }}

  ## Modules
  {{ .Modules }}

  ## Resources
  {{ .Resources }}

  ## Inputs
  {{ .Inputs }}

  ## Outputs
  {{ .Outputs }}

output:
  file: README.md
  mode: replace 