# Global settings shared across all resources
global:
  environment: production  # Current environment (production/staging/development)

# Backend service configuration
backend:
  name: item-service      # Service name
  image:
    repository: item-service  # Docker image repository
    tag: latest                            # Docker image tag
    pullPolicy: Never                     # Image pull policy
  replicas: 1            # Number of pod replicas
  service:
    type: ClusterIP      # Kubernetes service type
    port: 8080          # Service port
  resources:            # Resource limits and requests
    limits:
      cpu: 1000m        # CPU limit (1 core)
      memory: 2Gi      # Memory limit
    requests:
      cpu: 1000m         # CPU request
      memory: 2Gi    # Memory request
  database:
    secretName: item-management-mariadb
    url: jdbc:mariadb://host.docker.internal:3306/itemdb
# Frontend configuration
frontend:
  name: item-ui         # Service name
  image:
    repository: sandbox-project-ui  # Docker image repository
    tag: latest                       # Docker image tag
    pullPolicy: Never                # Image pull policy
  replicas: 1         # Number of pod replicas
  service:
    type: LoadBalancer # Kubernetes service type
    port: 80          # Service port
  resources:          # Resource limits and requests
    limits:
      cpu: 1000m       # CPU limit
      memory: 2Gi  # Memory limit
    requests:
      cpu: 1000m       # CPU request
      memory: 2Gi  # Memory request

