FROM node:18-alpine
WORKDIR /app
RUN npm install -g @angular/cli
COPY package*.json ./
ENV NODE_OPTIONS=--max_old_space_size=4096

RUN  npm install
COPY . .
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll=1000"]